revert some dependency bumps, it was introducing an issue.
Exception ignored in: <function _removeHandlerRef at 0x107640360>
Traceback (most recent call last):
...
RuntimeError: greenlet is being finalized